# Generated by Django 4.0.3 on 2022-03-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0002_departamento_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
