# Generated by Django 4.0.3 on 2022-03-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0003_alter_empleado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
